redis:
  database: mall
  key:
    user: 'mall:user'
    account: 'backstage:account'
    resourceList: 'mall:resourceList'
  expire:
    common: 86400 # 24小时


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: admin-secret #JWT加解密使用的密钥
  expiration: 86400 #JWT的超期限时间(60*60*24)  一天
  tokenHead: Bearer  #JWT负载中拿到开头
